import { useState, useEffect } from 'react'
import Head from 'next/head'

export default function Home() {
    const [message, setMessage] = useState('unset')

    useEffect(() => {
        fetch('http://localhost:4060')
            .then((res) => res.json())
            .then(({ message }) => setMessage(message))
            .catch((err) => console.error(err))
    }, [])
    return (
        <div>
            <Head>
                <title>Home</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <p>Hello World!</p>
                <p>Message is: {message} </p>
            </main>
        </div>
    )
}
